### PR TITLE
Fixes the linter error

### PR DESCRIPTION
**Pull request by samimsu**
### What this PR does (required):
- It fixes the '**Delete \`␍\`  prettier/prettier**' error.

### Screenshots / Videos (required):
image

### Any information needed to test this feature (required):
- `cd client`
- `npm start`

### CODE REVIEW

**Review by sina-jamshidi — APPROVED** [review]

**Review by ahmed-belhadj — COMMENTED** [review]
Does this turn off prettier rules? Maybe we can configure a script in package.json instead?

**Comment by samimsu** [comment]
Resolved. I changed VS Code settings. No need to merge.

**Comment by samimsu** [comment]
I'll close the PR without merging. Here's the setting I changed in VS code:
image
Changed '**Prettier: End of Line**' to '**auto**'.

**Review by samimsu — COMMENTED** [review]
Looks good. We can merge this.

**Pull request merged**
